version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      HOST: "db"
  db:
    image: "postgres"
    environment:
      POSTGRES_DB: backend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres